name: Deploying main Branch
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted, react-app3-runner]
    env:
      PM2_PROCESS_NAME: react-app-3
      PORT: 3002
      node-version: 18
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Create build
        run: npm run build
      - name: Start or Reload the Application
        run: |
          if pm2 list | grep -q "$PM2_PROCESS_NAME"; then
            echo "Process $PM2_PROCESS_NAME exists. Reloading..."
            pm2 reload "$PM2_PROCESS_NAME"
          else
            echo "Process $PM2_PROCESS_NAME does not exist. Starting..."
            pm2 start "serve -s build -l $PORT" --name "$PM2_PROCESS_NAME"
          fi
          pm2 save
